# permissions for end users to view etcdbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdbackup-viewer-role
rules:
- apiGroups:
  - etcd.oschina.cn
  resources:
  - etcdbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.oschina.cn
  resources:
  - etcdbackups/status
  verbs:
  - get
